cache: bundler
language: ruby
sudo: false
env:
  RAILS_ENV=test
  DB=postgresql
  SECRET_KEY_BASE="$(bundle exec rake secret)"
before_script: 
  - rake db:create
  - rake db:schema:load
script:
  - rake spec
