cache: bundler
language: ruby
sudo: false
env:
  RAILS_ENV=test
  DB=postgresql
  SECRET_KEY_BASE="$(bundle exec rake secret)"
script: 
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rake spec
before_script:
