language: ruby
rvm:
  - 2.2.5
bundler_args: --jobs=2
env:
  - SECRET_KEY_BASE="$(bundle exec rake secret)"
  - TESTOPTS='-v --seed 3717' # Looking for consistent failure
#   DB=postgresql
script:
  - bundle exec rake db:setup
  - bundle exec rake test
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
