cache: bundler
language: ruby
rvm:
  - "2.1.2"
sudo: false
env:
  RAILS_ENV=test
  DB=postgresql
  SECRET_KEY_BASE="$(bundle exec rake secret)"
script: 
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake spec
before_script:
  - psql -c 'create database marysplace_test' -U postgres
