app:
  build: .
  command: rails server -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
postgres:
  image: postgres:9.5.12
  ports:
    - '5432:5432'
  volumes:
    - ./db_backups:/db_backups
